
services:
  backend:
    build: .
    container_name: forum-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/forumdb
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: forum-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forumdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: forum-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  # 🔥 NEW FRONTEND SERVICE 🔥
  frontend:
    build: ../frontend2/frontend
    container_name: forum-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: