"""add cascade delete to votes

Revision ID: 35dd5f91efa4
Revises: 04f779290a78
Create Date: 2025-12-05 10:49:21.469468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35dd5f91efa4'
down_revision: Union[str, Sequence[str], None] = '04f779290a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('votes_user_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_user_id_fkey'), 'votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
